services:
  db:
    image: postgres:14.17-bookworm
    container_name: phonium_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: phonium
    ports:
      - "5432:5432"
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
      - phonium_db:/var/lib/postgresql/data

  adminer:
    build:
      dockerfile: adminer.Dockerfile
    ports:
      - "8081:8080"

volumes:
  phonium_db: