#docker compose -f prod-docker-compose.yaml up
services:
  api:
    build:
      dockerfile: api.Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: phonium
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14.17-bookworm
    container_name: phonium_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: phonium
    ports:
      - "5432:5432"
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
      - phonium_prod_db:/var/lib/postgresql/data

  adminer:
    build:
      dockerfile: adminer.Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  phonium_prod_db:

