services:
  api:
    build:
      dockerfile: ./api.Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: phonium
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - backend
      - db
    depends_on:
      - db

  db:
    image: postgres:14.17-bookworm
    container_name: phonium_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: phonium
    ports:
      - "5432:5432"
    networks:
      - db
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
      - phonium_prod_db:/var/lib/postgresql/data

  proxy:
    build:
      dockerfile: ./proxy.Dockerfile
    environment:
      VITE_API_URL: api
    restart: unless-stopped
    depends_on:
      - db
      - api
    ports:
      - "5173:80"
    networks:
      - backend
      - outer

networks:
  backend:
  db:
  outer:

volumes:
  phonium_prod_db:
